services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    tty: true
    ports:
      - 8080:80
    networks:
      - node-network
    depends_on:
      app:
        condition: service_healthy

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: app
    networks:
      - node-network
    volumes:
      - ./src:/app  # Caminho no host -> Caminho absoluto no contêiner
      - /app/node_modules  # Caminho absoluto no contêiner => ->
    tty: true
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3000/"]
      interval: 5s
      timeout: 30s
      retries: 6

networks:
  node-network:
    driver: bridge
